import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

// Import autogenerated fontawesome imports
import "./plugins/fontawesome-autoimport.js";

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
